/**
 * B3.2+ — Catalogue officiel exploitable (gouvernance, pas runtime métier).
 */

import {
  OFFICIAL_ERP_EVENT_TYPES,
  type OfficialErpEventType,
} from "@/lib/erp-core/events/event-taxonomy";
import type { ErpEventFamily } from "@/lib/erp-core/events/event-contracts";

export const ERP_EVENT_CATALOG_VERSION = "erp-event-catalog-bloc3-platform-v1" as const;

export type ErpEventCatalogStatus =
  | "active"
  | "partial"
  | "catalog_only"
  | "planned";

export type ErpEventCatalogEntry = {
  type: OfficialErpEventType;
  family: ErpEventFamily;
  status: ErpEventCatalogStatus;
  owner: string;
  publisher: string | null;
  wiredAt: string | null;
  notes: string;
};

/** Cartographie officielle — statut d'exploitation au runtime. */
export const ERP_EVENT_GOVERNANCE_MAP: readonly ErpEventCatalogEntry[] = [
  {
    type: OFFICIAL_ERP_EVENT_TYPES.APPROVAL_REQUEST_CREATED,
    family: "approval",
    status: "active",
    owner: "approval-engine",
    publisher: "integrations/approval-events.ts",
    wiredAt: "lib/erp-core/approval/mutation-gate.ts",
    notes: "Émis à la création d'une demande pending.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.APPROVAL_REQUEST_APPROVED,
    family: "approval",
    status: "active",
    owner: "approval-engine",
    publisher: "integrations/approval-events.ts",
    wiredAt: "app/(app)/admin/approvals/actions.ts",
    notes: "Post decideApprovalRequest approved.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.APPROVAL_REQUEST_REJECTED,
    family: "approval",
    status: "active",
    owner: "approval-engine",
    publisher: "integrations/approval-events.ts",
    wiredAt: "app/(app)/admin/approvals/actions.ts",
    notes: "Post decideApprovalRequest rejected.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.APPROVAL_GATE_GRANTED,
    family: "approval",
    status: "active",
    owner: "approval-engine",
    publisher: "integrations/approval-events.ts",
    wiredAt: "lib/erp-core/approval/mutation-gate.ts",
    notes: "Demande déjà approved — mutation autorisée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.MUTATION_BLOCKED_PENDING,
    family: "mutation",
    status: "active",
    owner: "mutation-gate",
    publisher: "integrations/approval-events.ts",
    wiredAt: "lib/erp-core/approval/mutation-gate.ts",
    notes: "Tentative mutation alors que pending.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_QUOTE_CONVERTED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/quote-sale-conversion.ts",
    notes: "Post-RPC convert_crm_quote_to_sale.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_QUOTE_CONVERT_REQUESTED,
    family: "mutation",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/quote-sale-conversion.ts",
    notes: "Émis pré-gate (intention conversion).",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.RUNTIME_ORCHESTRATION_COMPLETED,
    family: "runtime",
    status: "active",
    owner: "runtime",
    publisher: "integrations/crm-events.ts",
    wiredAt: "emitCrmQuoteConverted",
    notes: "Émis avec convert quote.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.RUNTIME_ORCHESTRATION_FAILED,
    family: "runtime",
    status: "active",
    owner: "runtime",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/quote-sale-conversion.ts",
    notes: "Échec RPC, payload invalide ou assert orchestration.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_LEAD_CREATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#createCrmLead",
    notes: "P1.1 — post-insert, avant audit legacy.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_QUOTE_CREATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#createCrmQuote",
    notes: "P1.1 — post-insert, avant audit legacy.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_QUOTE_STATUS_UPDATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#updateCrmQuoteStatus",
    notes: "P1.1 — post-update, avant audit legacy.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_LEAD_UPDATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#updateCrmLeadStatus",
    notes: "Bloc 3 — transition statut lead.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_LEAD_CONVERTED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#convertCrmLeadToClient",
    notes: "Bloc 3 — lead → client.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_PIPELINE_UPDATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#updateCrmOpportunityStage",
    notes: "Bloc 3 — changement étape opportunité.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_DEAL_CREATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#createCrmOpportunity",
    notes: "Bloc 3 — opportunité créée (deal).",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_DEAL_WON,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#updateCrmOpportunityStage",
    notes: "Bloc 3 — étape terminal win.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_DEAL_LOST,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#updateCrmOpportunityStage",
    notes: "Bloc 3 — étape terminal loss.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_ACTIVITY_CREATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#createCrmActivity",
    notes: "Bloc 3 — follow-up / activité créée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_ACTIVITY_COMPLETED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-mutations.ts#completeCrmActivity",
    notes: "Bloc 3 — activité clôturée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.CRM_REPORT_GENERATED,
    family: "domain",
    status: "active",
    owner: "vente-crm",
    publisher: "integrations/crm-events.ts",
    wiredAt: "modules/crm/server/services/crm-analytics-service.ts",
    notes: "Bloc 3 — rapport analytics opérationnel.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_TRANSACTION_RECORDED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-transaction-mutations.ts",
    notes: "Bloc 3 — FT expense / journal post.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_TRANSACTION_FAILED,
    family: "domain",
    status: "catalog_only",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: null,
    notes: "P4 — échec RPC journal / FT ; pas d'émission avant gate activé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_THRESHOLD_EXCEEDED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "lib/finance/runtime/finance-threshold-evaluator.ts#evaluateAndEmitFinanceTreasuryThresholds",
    notes: "P6.1 — KPI trésorerie → bus ; bridge P5 + automation P6.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_PAYMENT_RECORDED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-transaction-mutations.ts",
    notes: "Bloc 3 — allocation paiement lue.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_EXPENSE_CREATED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-expense-mutations.ts#createFinanceExpense",
    notes: "P4.1 — post-RPC, parallèle audit governance.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_EXPENSE_UPDATED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-expense-mutations.ts#updateFinanceExpense",
    notes: "P4.1 — post-RPC, parallèle audit governance.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_TRANSACTION_UPDATED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-expense-mutations.ts",
    notes: "Bloc 3 — mise à jour dépense / FT.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_APPROVAL_REQUESTED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-journal-mutations.ts",
    notes: "Bloc 3 — soumission lot journal.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_APPROVAL_APPROVED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-journal-mutations.ts",
    notes: "Bloc 3 — comptabilisation lot.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_APPROVAL_REJECTED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-journal-mutations.ts",
    notes: "Bloc 3 — rejet lot journal.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.FINANCE_REPORT_GENERATED,
    family: "domain",
    status: "active",
    owner: "finance",
    publisher: "integrations/finance-events.ts",
    wiredAt: "modules/finance/server/services/finance-reporting-service.ts",
    notes: "Bloc 3 — rapport opérationnel généré.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_EMPLOYEE_CREATED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-recruitment-mutations.ts#linkHrCandidateToEmployeeDomain",
    notes: "P9 — onboarding embauche (rattachement profil).",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_EMPLOYEE_UPDATED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-employee-mutations.ts",
    notes: "P7.1 — role/manager update post-write.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_CONTRACT_CREATED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-contract-mutations.ts#createHrContract",
    notes: "P7.1 — brouillon contrat ; activation = approval SQL.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_CONTRACT_SUBMITTED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-contract-lifecycle-mutations.ts#submitHrContractForApproval",
    notes: "P9 — soumission approbation ; remplace tryCreateAlert pending.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_CONTRACT_EXPIRING,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "lib/hr/runtime/hr-contract-expiry-evaluator.ts#evaluateAndEmitHrContractExpiringEvents",
    notes: "P7.3 — snapshot contrats + transition renewal_due ; bridge + automation.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_CONTRACT_EXPIRED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-contract-lifecycle-mutations.ts#transitionHrContractStatus",
    notes: "P9 — cycle de vie contrat expiré.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_CONTRACT_TERMINATED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-contract-lifecycle-mutations.ts#transitionHrContractStatus",
    notes: "P9 — cycle de vie contrat terminé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_CONTRACT_RENEWED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-contract-lifecycle-mutations.ts#renewHrContract",
    notes: "P9 — renouvellement date fin ; remplace tryCreateAlert renewed.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_RECRUITMENT_HIRE_SUBMITTED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-recruitment-mutations.ts#submitHrRecruitmentHire",
    notes: "P9 — embauche soumise approbation ; remplace tryCreateAlert hire_pending.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_LEAVE_REQUESTED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-leave-mutations.ts#submitHrLeaveRequest",
    notes: "P7.1 — post-insert + approval row.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_LEAVE_APPROVED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-leave-mutations.ts#updateHrLeaveStatus",
    notes: "P7.1 — émis si status approved uniquement.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_LEAVE_REJECTED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-leave-mutations.ts#updateHrLeaveStatus",
    notes: "Bloc 3 — rejet congé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_ATTENDANCE_RECORDED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-attendance-mutations.ts#recordHrAttendance",
    notes: "Bloc 3 — pointage.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.HR_EMPLOYEE_STATUS_CHANGED,
    family: "domain",
    status: "active",
    owner: "hr",
    publisher: "integrations/hr-events.ts",
    wiredAt: "modules/hr/server/services/hr-employee-mutations.ts#updateHrEmployeeEmploymentStatus",
    notes: "Bloc 3 — statut employé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_SUPPLIER_CREATED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#createLogisticsSupplier",
    notes: "Bloc 3 — fournisseur créé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_PURCHASE_REQUESTED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#submitLogisticsPurchaseOrder",
    notes: "Bloc 3 — PO soumis.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_PURCHASE_APPROVED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#approveLogisticsPurchaseOrder",
    notes: "Bloc 3 — PO approuvé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_PO_CREATED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#createLogisticsPurchaseOrder",
    notes: "Bloc 3 — commande achat brouillon.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_INVENTORY_RECEIVED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#createLogisticsGoodsReceipt",
    notes: "Bloc 3 — réception marchandises.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_STOCK_ADJUSTED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#adjustLogisticsStock",
    notes: "Bloc 3 — ajustement stock.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_INVENTORY_MOVED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-mutations.ts#transferLogisticsStock",
    notes: "Bloc 3 — transfert inter-entrepôts.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SUPPLY_REPORT_GENERATED,
    family: "domain",
    status: "active",
    owner: "logistics",
    publisher: "integrations/supply-events.ts",
    wiredAt: "modules/logistics/server/services/logistics-analytics-service.ts",
    notes: "Bloc 3 — rapport supply opérationnel.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_TASK_CREATED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#createOpsTask",
    notes: "Bloc 3 Étape 5 — tâche créée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_TASK_ASSIGNED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#assignOpsTask",
    notes: "Bloc 3 Étape 5 — assignation exécutant.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_TASK_COMPLETED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#completeOpsTask",
    notes: "Bloc 3 Étape 5 — clôture tâche.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_WORKFLOW_STARTED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#startOpsWorkflow",
    notes: "Bloc 3 Étape 5 — workflow démarré.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_WORKFLOW_APPROVED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#transitionOpsWorkflow",
    notes: "Bloc 3 Étape 5 — workflow approuvé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_PROJECT_CREATED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#createOpsProject",
    notes: "Bloc 3 Étape 5 — projet gouverné.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_DELIVERY_COMPLETED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#completeOpsDelivery",
    notes: "Bloc 3 Étape 5 — jalon livré.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_EXECUTION_DELAYED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-mutations.ts#reportOpsDeliveryDelay",
    notes: "Bloc 3 Étape 5 — retard exécution.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OPS_REPORT_GENERATED,
    family: "domain",
    status: "active",
    owner: "operations",
    publisher: "integrations/ops-events.ts",
    wiredAt: "modules/operations/server/services/ops-analytics-service.ts",
    notes: "Bloc 3 Étape 5 — rapport operations.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.EXECUTIVE_SNAPSHOT_REFRESHED,
    family: "domain",
    status: "active",
    owner: "executive",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/executive-dashboard/server/repositories/executive-read-placeholder.ts",
    notes: "Bloc 3 Étape 6 — snapshot global rafraîchi.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.EXECUTIVE_KPI_THRESHOLD_EXCEEDED,
    family: "domain",
    status: "active",
    owner: "executive",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/executive-dashboard/server/services/executive-alerting-service.ts",
    notes: "Bloc 3 Étape 6 — seuil KPI BI.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.EXECUTIVE_FORECAST_GENERATED,
    family: "domain",
    status: "active",
    owner: "executive",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/executive-dashboard/server/services/executive-forecast-service.ts",
    notes: "Bloc 3 Étape 6 — forecast persisté.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.EXECUTIVE_SIGNAL_RAISED,
    family: "domain",
    status: "active",
    owner: "executive",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/executive-dashboard/server/services/executive-alerting-service.ts",
    notes: "Bloc 3 Étape 6 — signal exécutif.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.ANALYTICS_SNAPSHOT_COMPUTED,
    family: "domain",
    status: "active",
    owner: "executive",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/executive-dashboard/server/services/executive-bi-engine.ts",
    notes: "Bloc 3 Étape 6 — KPI snapshots BI.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.ANALYTICS_REPORT_GENERATED,
    family: "domain",
    status: "catalog_only",
    owner: "executive",
    publisher: "integrations/executive-events.ts",
    wiredAt: null,
    notes: "Rapport analytics consolidé — émission via actions dédiées.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OBSERVABILITY_HUB_REFRESHED,
    family: "domain",
    status: "active",
    owner: "observability",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/observability/server/services/observability-hub-digest.ts",
    notes: "Bloc 3 Étape 6 — hub observability rafraîchi.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OBSERVABILITY_HEALTH_DEGRADED,
    family: "domain",
    status: "active",
    owner: "observability",
    publisher: "integrations/executive-events.ts",
    wiredAt: "modules/observability/server/services/observability-hub-digest.ts",
    notes: "Bloc 3 Étape 6 — score santé dégradé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.OBSERVABILITY_INCIDENT_ESCALATED,
    family: "domain",
    status: "catalog_only",
    owner: "observability",
    publisher: "integrations/executive-events.ts",
    wiredAt: null,
    notes: "Escalade incident — wiring mutation incidents phase ultérieure.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.SYSTEM_AUDIT_RECORDED,
    family: "audit",
    status: "planned",
    owner: "governance",
    publisher: null,
    wiredAt: null,
    notes: "Pont audit legacy → bus (phase ultérieure).",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_RULE_TRIGGERED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "lib/erp-core/events/automation/automation-rule-engine.ts",
    notes: "Bloc 3 Étape 7 — règle matchée avant exécution handler.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_RULE_EXECUTED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "lib/erp-core/events/automation/automation-rule-engine.ts",
    notes: "Bloc 3 Étape 7 — handler exécuté avec succès.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_RULE_FAILED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "lib/erp-core/events/automation/automation-rule-engine.ts",
    notes: "Bloc 3 Étape 7 — échec handler ou safety gate.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_WORKFLOW_STARTED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "modules/automation/server/services/automation-workflow-run-tick.ts",
    notes: "Run workflow démarré.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_WORKFLOW_COMPLETED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "modules/automation/server/services/automation-workflow-run-tick.ts",
    notes: "Run workflow terminé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_CROSS_DOMAIN_ORCHESTRATED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "lib/erp-core/events/handlers/automation-orchestration-bridge.ts",
    notes: "Bloc 3 Étape 7 — chaîne multi-domaines tracée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_AI_RECOMMENDATION_GENERATED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "modules/ai/server/services/ai-decision-support-orchestration.ts",
    notes: "Recommandation structurée persistée erp_ai_recommendations.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_AI_DECISION_SUPPORT_EMITTED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "lib/erp-core/events/handlers/ai-orchestration-bridge.ts",
    notes: "Decision support gouverné (confiance + source).",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.AUTOMATION_REPORT_GENERATED,
    family: "domain",
    status: "active",
    owner: "automation",
    publisher: "integrations/automation-events.ts",
    wiredAt: "modules/automation/server/services/automation-cockpit-digest.ts",
    notes: "Rapport cockpit automation publié.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_API_REGISTERED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "lib/platform/governance/api-governance-registry.ts",
    notes: "Bloc 3 Étape 8 — API enregistrée au registry.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_API_INVOKED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "lib/platform/runtime/api-invocation-guard.ts",
    notes: "Invocation API auditée (rate limit + log).",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_INTEGRATION_CONNECTED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "modules/platform/server/services/integration-framework-service.ts",
    notes: "Intégration connectée tenant-scoped.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_CONNECTOR_HEALTH_DEGRADED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "modules/platform/server/services/connector-engine-service.ts",
    notes: "Santé connecteur dégradée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_CONNECTOR_SYNC_COMPLETED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "modules/platform/server/services/connector-engine-service.ts",
    notes: "Sync connecteur terminée.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_PLUGIN_INSTALLED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "modules/platform/server/services/plugin-lifecycle-service.ts",
    notes: "Plugin installé / activé.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_MARKETPLACE_LISTING_PUBLISHED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "modules/platform/server/services/marketplace-catalog-service.ts",
    notes: "Listing marketplace publié.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_DEVELOPER_SANDBOX_READY,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "lib/platform/runtime/developer-ecosystem-registry.ts",
    notes: "Sandbox développeur prêt.",
  },
  {
    type: OFFICIAL_ERP_EVENT_TYPES.PLATFORM_REPORT_GENERATED,
    family: "domain",
    status: "active",
    owner: "platform",
    publisher: "integrations/platform-events.ts",
    wiredAt: "modules/platform/server/services/platform-cockpit-digest.ts",
    notes: "Rapport cockpit plateforme.",
  },
] as const;

export function listAutomationGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("automation."));
}

export function listPlatformGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("platform."));
}

export function listCrmGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("crm."));
}

export function listSupplyGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("supply."));
}

export function listOpsGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("ops."));
}

export function listExecutiveGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter(
    (e) =>
      e.type.startsWith("executive.") ||
      e.type.startsWith("analytics.") ||
      e.type.startsWith("observability."),
  );
}

export function listFinanceGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("finance."));
}

export function listHrGovernanceEvents(): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.type.startsWith("hr."));
}

export function listEventsByFamily(family: ErpEventFamily): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.family === family);
}

export function listEventsByStatus(status: ErpEventCatalogStatus): ErpEventCatalogEntry[] {
  return ERP_EVENT_GOVERNANCE_MAP.filter((e) => e.status === status);
}
