import type { AuditEventType, AuditSeverity } from "@/lib/audit/audit-types";

export const AUDIT_EVENT_TYPES = {
  USER_INVITED: "USER_INVITED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  MANAGER_REPLACED: "MANAGER_REPLACED",
  CLIENT_DELETED: "CLIENT_DELETED",
  PRODUCT_ARCHIVED: "PRODUCT_ARCHIVED",
  SALE_DELETED: "SALE_DELETED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  BULK_OPERATION: "BULK_OPERATION",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_RESET: "PASSWORD_RESET",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",
} as const satisfies Record<AuditEventType, AuditEventType>;

export const AUDIT_DEFAULT_SEVERITY: Record<AuditEventType, AuditSeverity> = {
  USER_INVITED: "medium",
  USER_ROLE_CHANGED: "high",
  MANAGER_REPLACED: "critical",
  CLIENT_DELETED: "high",
  PRODUCT_ARCHIVED: "medium",
  SALE_DELETED: "critical",
  EXPENSE_UPDATED: "high",
  BULK_OPERATION: "high",
  LOGIN_SUCCESS: "low",
  LOGIN_FAILED: "medium",
  PASSWORD_RESET: "medium",
  APPROVAL_GRANTED: "high",
  APPROVAL_REJECTED: "high",
};
